/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const dsh_voice_input_voiceInput_cleanup_parameter_0$schema = z.object({
  'text': z.string().readonly(),
  'model': z.object({
  'provider': z.string().readonly(),
  'model': z.string().readonly(),
  'reasoningEffort': z.string().readonly().optional(),
}).readonly(),
})
const dsh_voice_input_voiceInput_cleanup_result$schema = z.object({
  'text': z.string().readonly(),
  'changed': z.boolean().readonly(),
})

export const TYPERT = {
  package: 'dsh-voice-input',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-voice-input#voiceInput/cleanup',
      service: 'voiceInput',
      namespace: 'voiceInput',
      method: 'cleanup',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-voice-input/types#CleanupRequest',
            schema: dsh_voice_input_voiceInput_cleanup_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-voice-input/types#CleanupResponse',
        schema: dsh_voice_input_voiceInput_cleanup_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-voice-input/src/index.ts","line":52,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "Host service exposed to the browser through a generated Typert Remote.",
        "summary": "Host service exposed to the browser through a generated Typert Remote.",
        "tags": [],
        "jsDoc": "/** Host service exposed to the browser through a generated Typert Remote. */",
        "key": "voiceInput",
        "exportName": "VoiceInputService",
        "members": [
          {
            "kind": "method",
            "name": "cleanup",
            "signature": "@Remote('cleanup') async cleanup(request: CleanupRequest, signal: AbortSignal): Promise<CleanupResponse>",
            "summary": "Clean one transcript with the model selected by the addressed browser Session.",
            "jsDoc": "/**\n * Clean one transcript with the model selected by the addressed browser\n * Session. The Client resolves the selection immediately before this call;\n * the Host supplies credentials and routing through the normal Harness LLM.\n */"
          }
        ],
        "types": [
          {
            "name": "CleanupRequest",
            "declaration": "export interface CleanupRequest {\n    readonly text: string;\n    readonly model: VoiceModelSelection;\n}"
          },
          {
            "name": "CleanupResponse",
            "declaration": "export interface CleanupResponse {\n    readonly text: string;\n    readonly changed: boolean;\n}"
          },
          {
            "name": "VoiceModelSelection",
            "declaration": "export interface VoiceModelSelection {\n    readonly provider: string;\n    readonly model: string;\n    readonly reasoningEffort?: string;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
