/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { CleanupRequest, CleanupResponse } from 'dsh-voice-input/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$766f696365496e707574 {
    cleanup: (request: CleanupRequest, signal?: AbortSignal) => Promise<RemoteResult<CleanupResponse>>
  }
  interface TypertRemoteMap {
    'voiceInput/cleanup': (request: CleanupRequest, signal?: AbortSignal) => Promise<RemoteResult<CleanupResponse>>
  }
  interface TypertRemoteNamespaceMap {
    'voiceInput': TypertRemoteNamespace$766f696365496e707574
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
